global:
  environment:
    - name: GROQ_API_KEY
      value: ''
    - name: WEBHOOK_SECRET
      value: 'agent-flow-webhook-secret-2024'

hasura:
  version: 'v2.38.0-ce'
  adminSecret: 'nhost-admin-secret'
  settings:
    corsDomain: ['*']
    devMode: true
    enableAllowList: false
    enableConsole: true
    enableRemoteSchemaPermissions: false
    enabledAPIs:
      - metadata
      - graphql
      - pgdump
      - config
    liveQueriesMultiplexedRefetch: 1000
    stringifyNumericTypes: false

functions:
  node:
    version: 18

auth:
  method:
    emailPassword:
      emailVerificationRequired: false
      hibpEnabled: false
    anonymous:
      enabled: false
  redirections:
    clientUrl: http://localhost:3000
  signUp:
    enabled: true

postgres:
  version: '14.6-20230705-1'

storage:
  version: '0.3.5'
