[global]

[[global.environment]]
name = "GROQ_API_KEY"
value = ""

[[global.environment]]
name = "WEBHOOK_SECRET"
value = "agent-flow-webhook-secret-2024"

[hasura]
version = "v2.38.0-ce"
adminSecret = "nhost-admin-secret"

[hasura.settings]
corsDomain = ["*"]
devMode = true
enableAllowList = false
enableConsole = true
enableRemoteSchemaPermissions = false
enabledAPIs = ["metadata", "graphql", "pgdump", "config"]

[functions]
[functions.node]
version = 18

[auth]
[auth.method.emailPassword]
emailVerificationRequired = false
hibpEnabled = false

[auth.method.anonymous]
enabled = false

[auth.redirections]
clientUrl = "http://localhost:3000"

[auth.signUp]
enabled = true

[postgres]
version = "14.6-20230705-1"

[storage]
version = "0.3.5"
